/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;

public class App {

    public static void main(String[] args) {

        System.out.println("Daily quotes");
        System.out.println(readJson().get(0));
        System.out.println();
        System.out.println("Swanson quotes");
        System.out.println(getQuotesFromAPI());
    }

    public String getGreeting() {

        return "Hello world.";
    }

    public static ArrayList readJson(){

        try {
            File file = new File("src/main/resources/recentquotes.json");
            FileReader reader = new FileReader(file);
            Gson gson = new Gson();
            Quote[] response = gson.fromJson(reader, Quote[].class);

            int min = 0;
            int max = response.length;
            int range = max - min + 1;
            int random = (int) (Math.random() * range) + min;
            ArrayList<Quote> quotelist = new ArrayList<Quote>();
            quotelist.add(response[random]);

            return quotelist;

        }
        catch (FileNotFoundException e) {
            e.printStackTrace();
            return null;
        }
    }

    public static String getQuotesFromAPI(){
        try {
            URL url = new URL("https://ron-swanson-quotes.herokuapp.com/v2/quotes");
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            BufferedReader reader = new BufferedReader(new InputStreamReader((con.getInputStream())));
            Gson gson = new Gson();
            String[] randomQuote = gson.fromJson(reader, String[].class);

            File file = new File("src/main/resources/recentquotes.json");
            FileReader reader2 = new FileReader(file);
            Quote[] response = gson.fromJson(reader2, Quote[].class);

            Quote q = new Quote("Ron Swanson", randomQuote[0], new String[]{}, "0 likes" );
            Quote[] result = new Quote[response.length + 1];
            for(int i = 0; i < response.length; i++) {
                result[i] = response[i];
            }
            result[response.length] = q;

            String finalResults = gson.toJson(result);

            try (FileWriter file2 = new FileWriter("src/main/resources/recentquotes.json")) {
                file2.write(finalResults);
            }

            return randomQuote[0];

        }
        catch (IOException e) {
            System.out.println(readJson().get(0));
            return null;
        }
    }



}
